name "ckan"
description "Installs and configures CKAN for development."
version "0.1.0"
maintainer "Vitor Baptista"
maintainer_email "vitor@vitorbaptista.com"
license "Apache v2.0"

depends "apt"
depends "git"
depends "python"
depends "database"
depends "postgresql"
depends "build-essential"
depends "java"
